# Generated by Django 3.1.7 on 2021-03-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_child'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='age',
            new_name='birthMonth',
        ),
        migrations.AddField(
            model_name='child',
            name='birthYear',
            field=models.IntegerField(default=2015),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='child',
            name='img',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='pin_code',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
