# Generated by Django 3.1.7 on 2021-03-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_auto_20210318_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='birthMonth',
            new_name='age',
        ),
        migrations.RemoveField(
            model_name='child',
            name='birthYear',
        ),
        migrations.AlterField(
            model_name='child',
            name='img',
            field=models.IntegerField(),
        ),
    ]
