# Generated by Django 3.1.7 on 2021-03-30 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_child_voice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='age',
            new_name='year',
        ),
    ]
