# Generated by Django 3.1.7 on 2021-03-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_auto_20210330_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authenticatecode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='pin_code',
            field=models.CharField(max_length=255),
        ),
    ]
