# Generated by Django 3.1.7 on 2021-03-23 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounts', '0006_auto_20210323_1626'),
        ('Words', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=20)),
                ('part', models.CharField(max_length=10)),
                ('mean', models.CharField(max_length=50)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.child')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='word',
            name='alphabet',
        ),
        migrations.DeleteModel(
            name='Alphabet',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
