# Generated by Django 3.1.7 on 2021-03-18 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.diary')),
            ],
        ),
    ]
