# Generated by Django 3.1.7 on 2021-03-18 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0004_auto_20210318_2147'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiaryToSentence',
        ),
    ]
