# Generated by Django 3.1.7 on 2021-03-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0014_diary_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='img',
            field=models.ImageField(upload_to='%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='note',
            name='img',
            field=models.ImageField(upload_to='%Y/%m/%d'),
        ),
    ]
