# Generated by Django 3.1.7 on 2021-03-25 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0020_auto_20210325_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='state',
            field=models.BooleanField(),
        ),
    ]
