# Generated by Django 3.1.7 on 2021-03-18 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20210318_1854'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Notes', '0002_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='child',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Accounts.child'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentence',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Accounts.user'),
            preserve_default=False,
        ),
    ]
