# Generated by Django 3.1.7 on 2021-03-23 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounts', '0005_auto_20210321_0237'),
        ('Notes', '0012_alphabet_word_wordtosentence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='word',
        ),
        migrations.RemoveField(
            model_name='word',
            name='alphabet',
        ),
        migrations.RemoveField(
            model_name='word',
            name='mean',
        ),
        migrations.RemoveField(
            model_name='word',
            name='part',
        ),
        migrations.AddField(
            model_name='word',
            name='child',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Accounts.child'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Accounts.user'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Alphabet',
        ),
    ]
