# Generated by Django 3.1.7 on 2021-03-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0013_auto_20210323_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
