# Generated by Django 3.1.7 on 2021-03-25 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0017_auto_20210325_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
