# Generated by Django 3.1.7 on 2021-03-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0018_word_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordtosentence',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
