# Generated by Django 3.1.7 on 2021-03-25 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0019_wordtosentence_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordtosentence',
            name='state',
        ),
        migrations.AddField(
            model_name='word',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
