# Generated by Django 3.1.7 on 2021-03-25 08:11

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0022_auto_20210325_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='img',
            field=imagekit.models.fields.ProcessedImageField(upload_to='images/%Y/%m/%d'),
        ),
    ]
