# Generated by Django 3.1.7 on 2021-03-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0023_auto_20210325_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='img',
            field=models.ImageField(upload_to='images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='note',
            name='img',
            field=models.ImageField(upload_to='images/%Y/%m/%d'),
        ),
    ]
