# Generated by Django 3.1.7 on 2021-03-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0024_auto_20210325_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='vol',
        ),
        migrations.AddField(
            model_name='note',
            name='month',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='year',
            field=models.IntegerField(default=2021),
            preserve_default=False,
        ),
    ]
