# Generated by Django 3.1.7 on 2021-03-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0027_auto_20210329_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='note',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d'),
        ),
    ]
